apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: voting-app
    type: service
  namespace: voting-app

spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432

  selector:
    app: voting-app
    name: postgres-pod
    type: db