apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deployment
  labels:
    name: redis-deployment
    app: voting-app
    type: db
  namespace: voting-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: voting-app
      name: redis-pod
      type: db

  template:
    metadata: 
      name: redis-pod
      labels:
        app: voting-app
        name: redis-pod
        type: db

    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379


